---
title: "Study Area Maps"
author: "Melanie Dickie"
date: "10/03/2021"
output: html_document
---

```{r render, eval=FALSE, message=FALSE, warning=FALSE, include=FALSE, results='hide'}
```

## Load packages and data

```{r message=FALSE, warning=FALSE, results = 'hide'}

library(sf)
library(here)
library(readxl)
library(psych)
library(raster)
library(stringr)
library(lwgeom)
library(rworldmap)
library(rnaturalearth)
library(rmapshaper)
library(ggspatial)
library(tidyverse)
library(ggplot2)
library(cowplot)

##Load data for moose study area map
MooseSurveys <- st_read(here::here("data", "AB_WMU-OSR-Intersect.shp"))
OSRDensities<-read.csv(here::here("data", "OSRMooseEstimates_2014-2020.csv"))
MooseSurveys$WMUNIT_COD<-substr(MooseSurveys$WMUNIT_COD, 3,6)
MooseSurveysdens<-merge(MooseSurveys,OSRDensities, by= "WMUNIT_COD", all.x=TRUE) 

##Load home ranges and attribures
#Bring in home range polygons
all_SKest<-st_read(here::here("data", "allSKEst.shp"))
all_BCest<-st_read(here::here("data", "allBCEst.shp"))
all_RICCest<-st_read(here::here("data", "allRICCEst.shp"))
all_WHECest<-st_read(here::here("data", "allWHECEst.shp"))

##Bring in attributes from Attributing_NewaKDEs.R
all_estBuff<-read.csv(here::here("data", "All_estBuffEVILFDAttNoET.csv"))

##Bring in attributes for mapping aesthetics
all_SKest$LFD<-all_estBuff$LFD[match(all_SKest$name, all_estBuff$name)]
all_BCest$LFD<-all_estBuff$LFD[match(all_BCest$name, all_estBuff$name)]
all_RICCest$LFD<-all_estBuff$LFD[match(all_RICCest$name, all_estBuff$name)]
all_WHECest$LFD<-all_estBuff$LFD[match(all_WHECest$name, all_estBuff$name)]

all_SKest$EVIMean<-all_estBuff$EVIMean[match(all_SKest$name, all_estBuff$name)]
all_BCest$EVIMean<-all_estBuff$EVIMean[match(all_BCest$name, all_estBuff$name)]
all_RICCest$EVIMean<-all_estBuff$EVIMean[match(all_RICCest$name, all_estBuff$name)]
all_WHECest$EVIMean<-all_estBuff$EVIMean[match(all_WHECest$name, all_estBuff$name)]

all_SKest$ExtraTerr<-all_estBuff$ExtraTerr[match(all_SKest$name, all_estBuff$name)]
all_BCest$ExtraTerr<-all_estBuff$ExtraTerr[match(all_BCest$name, all_estBuff$name)]
all_RICCest$ExtraTerr<-all_estBuff$ExtraTerr[match(all_RICCest$name, all_estBuff$name)]
all_WHECest$ExtraTerr<-all_estBuff$ExtraTerr[match(all_WHECest$name, all_estBuff$name)]

##Load EVI layer for inset background
##Need to load a pre-processed .csv version for mapping because the raster is too large for git
Delta2020plot_df<-read.csv(here::here("data", "Delta2020plotdf.csv"))

#Load linear features for background
#Line layer too large to load to git.
#If you want lines added to map, download polylines from https://open.canada.ca/data/en/dataset/890a5d8d-3dbb-4608-b6ce-3b6d4c3b7dce
##Adding lines to map below is commented out
#lines = st_read(here::here("data", "EC_borealdisturbance_linear_2008_2010_FINAL_ALBERS.shp"))
#lines = lines %>% st_transform("+proj=aea +lat_1=50 +lat_2=70 +lat_0=40 +lon_0=-96 +x_0=0 +y_0=0 +ellps=GRS80 +datum=NAD83 +units=m +no_defs")


##Load provincial and national boundaries
provs<-read_sf("G:/My Drive/CMU/WolfHomeRange/Data/Provs.shp")%>%
  st_make_valid()%>%
  st_transform("+proj=aea +lat_1=20 +lat_2=60 +lat_0=40 +lon_0=-96 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs")
us <- ne_countries(country="United States of America", scale='medium',returnclass = 'sf')%>%
  st_transform("+proj=aea +lat_1=20 +lat_2=60 +lat_0=40 +lon_0=-96 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs")
can <- ne_countries(country="Canada", scale='medium',returnclass = 'sf')%>%
  st_transform("+proj=aea +lat_1=20 +lat_2=60 +lat_0=40 +lon_0=-96 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs")

```

## Create moose density and productivity study area map

```{r message=FALSE, warning=FALSE}
ggplot() +
  geom_raster(data = Delta2020plot_df, aes(x = x, y = y, fill=Delta2020plot))+
  scale_fill_gradient2(breaks=c(0, 2500,5000), n.breaks=10, low="brown4", mid="lightgrey", high="darkgreen",
                       guide=guide_colourbar(direction = "horizontal"), name = "delta EVI")+
  geom_sf(data = MooseSurveysdens, fill=NA, aes(colour=density_avg), size=1.5)+
  geom_sf(data = us, fill =NA, size=1) +
  geom_sf(data = can, fill =NA, size=1) +
  geom_sf(data = provs, fill = NA, size=1)+
  scale_colour_gradient(low = "yellow", high = "red", na.value = NA, breaks=c(0, 0.3,0.5), guide = guide_colourbar(direction = "horizontal"), name = expression(paste("Moose Density (/", km^2, ")")))+
  coord_sf(xlim =c(-1.7E6,-0.5E6), ylim = c(1.1E6, 2.5E6), crs="+proj=aea +lat_1=20 +lat_2=60 +lat_0=40 +lon_0=-96 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs") +
  theme(panel.grid.major = element_blank(),
        panel.background = element_rect(fill = "white"), 
        panel.border = element_rect(fill = NA),
        axis.text = element_blank(),
        axis.title = element_blank(),
        plot.margin=unit(c(0,0,0,0),"mm"),
        legend.position = "bottom",
        legend.background = element_blank())+
  annotation_scale(location = "bl", width_hint = 0.25)

```

## Create study area inset map

```{r message=FALSE, warning=FALSE}

##prep study area extents
extent = matrix(c(-1.8E6 ,1.2E6 , -1.8E6 , 2.8E6 , 0.1E6  , 2.8E6, 0.1E6 ,1.2E6 , -1.8E6 ,1.2E6 ),ncol=2, byrow=TRUE)
pts = list(extent)
pl1 = st_polygon(pts)
pl1 <- st_sfc(pl1, crs="+proj=aea +lat_1=20 +lat_2=60 +lat_0=40 +lon_0=-96 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs")%>%
  st_transform("+proj=laea +lat_0=40 +lon_0=-100 +x_0=4321000 +y_0=3210000 +ellps=GRS80 +units=m +no_defs")

##plot
mid <- median(Delta2020plot_df$Delta2020plot)
inset<-ggplot() +
  geom_raster(data = Delta2020plot_df, aes(x = x, y = y, fill=Delta2020plot))+
  scale_fill_gradient2(n.breaks=5, low="brown4", high="darkgreen", name = "delta EVI")+
  geom_sf(data=provs%>%st_transform("+proj=laea +lat_0=52 +lon_0=-100 +x_0=4321000 +y_0=3210000 +ellps=GRS80 +units=m +no_defs"), fill = "transparent", size=0.75)+
  #geom_sf(data = pl1, fill=NA, color="red", size = 0.5) +
  coord_sf(xlim =c(-2E6, 0.2E6), ylim = c(1.0E6, 2.9E6), crs="+proj=aea +lat_1=20 +lat_2=60 +lat_0=40 +lon_0=-96 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs") +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_rect(fill = "transparent"),
        panel.border = element_rect(fill = NA, color = "black"),
        axis.text = element_blank(),
        axis.title = element_blank(),
        plot.background = element_rect(colour = "black", size=1, fill="white"),
        legend.title = element_text(size = 8),
        legend.text = element_text(size = 7))
```

## Create study area map
```{r message=FALSE, warning=FALSE}
ggplot() +
  #geom_sf(data = lines, size=0.5, colour="grey")+
  geom_sf(data = us, fill =NA, size=1) +
  geom_sf(data = can, fill =NA, size=1) +
  geom_sf(data = provs, fill = NA, size=1)+
  geom_sf(data=subset(all_SKest, ExtraTerr==0), aes(colour=LFD), alpha=1/2, size=1)+
  geom_sf(data=subset(all_BCest, ExtraTerr ==0), aes(colour=LFD), alpha=1/2, size=1)+
  geom_sf(data=subset(all_RICCest, ExtraTerr==0), aes(colour=LFD), alpha=1/2, size=1)+
  geom_sf(data=subset(all_WHECest, ExtraTerr==0), aes(colour=LFD), alpha=1/2, size=1)+
  scale_colour_gradient(low = "yellow3", high = "red3", na.value = NA, breaks=c(0, 0.3,0.5), guide = guide_colourbar(direction = "horizontal"), name = expression(paste("Linear Feature Density (km/", km^2, ")")))+
  scale_fill_gradient(low = "yellow3", high = "red3", na.value = NA, breaks=c(0, 0.3,0.5), guide = guide_colourbar(direction = "horizontal"), name = expression(paste("Linear Feature Density (km/", km^2, ")")))+
  coord_sf(xlim =c(-1.7E6,-0.15E6), ylim = c(1.6E6, 2.7E6), crs="+proj=aea +lat_1=20 +lat_2=60 +lat_0=40 +lon_0=-96 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs") +
  theme(panel.grid.major = element_blank(),
        panel.background = element_rect(fill = "white"), 
        panel.border = element_rect(fill = NA),
        axis.text = element_blank(),
        axis.title = element_blank(),
        plot.margin=unit(c(0,0,0,0),"mm"),
        legend.position = "bottom",
        legend.background = element_blank())+
  annotation_scale(location = "bl", width_hint = 0.25)+
  annotation_custom(ggplotGrob(inset), xmin =-0.8E6, xmax = -0.14E6, ymin = 2.0E6, ymax = 3.1E6)
```
