---
title: "Supplemental Analyses"
author: "Melanie Dickie"
date: "08/03/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load packages and data


```{r message=FALSE, warning=FALSE}
require(stringr)
require(dplyr)
require(ggplot2)
require(cowplot)
require(nlme)
require(lme4)
require(broom)
require(broom.mixed)
require(lattice)


##Bring in main dataset:
DataLargerAvail<-read.csv(here::here("data", "All_estBuffEVILFDAtt.csv"))
##Make sure Extra-territorial home ranges identified previously are removed
DataLargerAvailNoET<-subset(DataLargerAvail, ExtraTerr == 0)
DataLargerAvailNoET<-subset(DataLargerAvailNoET, est <40000)#Extra-territorial movement also

##Scale delta EVI data
range01 <- function(x){(x-min(x,na.rm=TRUE))/(max(x,na.rm=TRUE)-min(x,na.rm=TRUE))}
DataLargerAvailNoET$EVIScaled<-range01(DataLargerAvailNoET$EVIMean)

DataLargerAvailNoET$AnimalYear<-paste(DataLargerAvailNoET$AnimalId, DataLargerAvailNoET$Year, sep="")
DataLargerAvailNoET$PackYear<-paste(DataLargerAvailNoET$PackID, DataLargerAvailNoET$Year, sep="")

#Subset to known packsize:
DataLargerAvailNoETPS<-subset(DataLargerAvailNoET, PackSize >1)

range01 <- function(x){(x-min(x,na.rm=TRUE))/(max(x,na.rm=TRUE)-min(x,na.rm=TRUE))}
DataLargerAvailNoETPS$EVIScaled<-range01(DataLargerAvailNoETPS$EVIMean)
```

## Test if including sex and pack size is supported in the top model


```{r message=FALSE, warning=FALSE}
modsexpshab3A<-lmer(log(est) ~ DiffDTScaled + Season + SA + LFD*EVIScaled + (1|PackYear), REML=FALSE, data = DataLargerAvailNoETPS)
modsexpshab3B<-lmer(log(est) ~ DiffDTScaled + Sex + Season + SA + LFD*EVIScaled + (1|PackYear), REML=FALSE, data = DataLargerAvailNoETPS)
modsexpshab3C<-lmer(log(est) ~ DiffDTScaled + PackSize + Season + SA + LFD*EVIScaled + (1|PackYear), REML=FALSE, data = DataLargerAvailNoETPS)
modsexpshab3D<-lmer(log(est) ~ DiffDTScaled + Sex + PackSize + Season + SA + LFD*EVIScaled + (1|PackYear), REML=FALSE, data = DataLargerAvailNoETPS)
AIC(modsexpshab3A, modsexpshab3B, modsexpshab3C, modsexpshab3D)
#Lowest AIC is the 3C - but it's within 2 AIC units.
##Does not support including pack size

#Test if Pack Size is significant
tablemodsexpshab3D<-tidy(modsexpshab3D)
tablemodsexpshab3D$CI<-1.96*tablemodsexpshab3D$std.error
tablemodsexpshab3D

```

## Test if pack size and sex explain the residuals of the full model
```{r message=FALSE, warning=FALSE}
meanx<-mean(DataLargerAvailNoET$EVIMean)
maxx<-max(DataLargerAvailNoET$EVIMean)
minx<-min(DataLargerAvailNoET$EVIMean)

wolflist<-unique(DataLargerAvailNoET$name)
pred.areadf <- data.frame()
for(i in wolflist){
  #print(i)
  testing <- subset(DataLargerAvailNoET, name == i)
  training <- subset(DataLargerAvailNoET, name != i)
  
  mymodel<-lmer(log(est) ~ DiffDTScaled + Season + SA + LFD*EVIScaled + (1|PackYear), REML=FALSE, data = training)
  testing$predArea <-  exp(predict(mymodel,testing, type=c("response"), re.form= ~(1|PackYear), allow.new.levels = TRUE))
  testing<-as.data.frame(testing)
  pred.areadf <- rbind(pred.areadf,testing)
}

pred.areadf$Dif<-pred.areadf$est-pred.areadf$predArea

##PackSize in the current dataframe is minimimum pack size estimated at capture
##Here I want to specifically look at pack size for that year
##There are a couple instances where pack size was estimated for > 1 year (because multiple captures)
##And instances where pack size wasn't estimated that year (because no captures)
##Because PackYear is the random intercept, I can use that information here
##In this analysis, only use pack size from the matching year

#PS is in MinimumPackSizes.csv
PackSizes<-read.csv(here::here("data", "MinimumPackSizes.csv"))
##There are multiple estimates per pack from multiple years
PackSizes$PackYear<-paste(PackSizes$PackID, PackSizes$Year, sep="")
pred.areadf$YearPackSize<-PackSizes$PackSize[match(pred.areadf$PackYear, PackSizes$PackYear)]

#Plot
PSPlot<-ggplot(data=subset(pred.areadf, Sex !="Unknown" & as.numeric(YearPackSize) <13), aes(x=as.factor(YearPackSize), y=(Dif))) +
  geom_boxplot(outlier.shape = NA)+
  geom_point(aes(shape=as.factor(SA)), size=2.5, alpha = 1/3)+
  scale_shape_discrete(name="Study Area", breaks=c("BC", "RICC", "WHEC", "SK"), solid=F)+
  theme_bw() +  
  geom_hline(yintercept=0, linetype="dashed")+
  xlab("Pack Size") +
  ylab("Residuals (Observed - Predicted)") +
  theme(axis.text.x = element_text(size=12), axis.title = element_text(size=14) ) + 
  theme(axis.text.y = element_text(size=12)) + 
  theme(panel.grid.minor=element_blank(), panel.grid.major=element_blank()) + 
  theme(legend.text = element_blank(),legend.title = element_blank(), legend.position="top", legend.box = "vertical")

pred.areadf$Sex[pred.areadf$Sex == "f"] <- "F"
SexPlot<-ggplot(data=subset(pred.areadf, Sex !="Unknown" & as.numeric(PackSize) <13), aes(x=(Sex), y=(Dif))) +
  geom_boxplot(outlier.shape = NA)+
  geom_point(aes(shape=as.factor(SA)), size=2.5, alpha = 1/3)+
  scale_shape_discrete(name="Study Area", breaks=c("BC", "RICC", "WHEC", "SK"), labels = c("BC", "AB NE", "AB N", "SK"), solid=F)+
  theme_bw() +  
  xlab("Sex") +
  geom_hline(yintercept=0, linetype="dashed")+
  ylab("") +
  theme(axis.text.x = element_text(size=12), axis.title = element_text(size=14) ) + 
  theme(axis.text.y = element_text(size=12)) + 
  theme(panel.grid.minor=element_blank(), panel.grid.major=element_blank()) + 
  theme(legend.text = element_text(size = 12),legend.title = element_text(size = 14), legend.position="top", legend.box = "vertical")

plot_grid(PSPlot, SexPlot, ncol = 2 , nrow = 1)

##Model
difsex<-lm(Dif ~ Sex, subset(pred.areadf, Sex != "Unknown"))
difPS<-lm(Dif ~ as.numeric(PackSize), subset(pred.areadf, as.numeric(PackSize) >0))
summary(difsex)
summary(difPS)

##The difference between obesrved and predicted home ranges is insignificantly larger for females than males
##The difference between observed and predicted home ranges is significantly larger as pack size increases
##Despite the effect of pack size being insignificant in models
##Though the plots suggest there may be a lack of data from larger packs
```

TEST IF RANDOM INTERCEPT DEVIATIONS ARE PREDICTED BY PACK SIZE
```{r message=FALSE, warning=FALSE}
##Extract BLUPs
str(rr1 <- ranef(modsexpshab3A))
str(dd <- as.data.frame(rr1))
dd$blup<-dd$condval+9.39324
 
##PackSize in the current dataframe is minimimum pack size estimated at capture
##Here I want to specifically look at pack size for that year
##There are a couple instances where pack size was estimated for > 1 year (because multiple captures)
##And instances where pack size wasn't estimated that year (because no captures)
##Because PackYear is the random intercept, I can use that information here
##In this analysis, only use pack size from the matching year

PackSizes$PackYear<-paste(PackSizes$PackID, PackSizes$Year, sep="")
dd$YearPackSize<-PackSizes$PackSize[match(dd$grp, PackSizes$PackYear)]

ggplot(data=dd, aes(x=(YearPackSize), y=(condval))) +
  geom_pointrange(aes(ymin = condval-2*condsd, ymax = condval+2*condsd), 
                  position=position_jitter(width=0.3), 
                  linetype='dashed')+
  theme_bw() +  
  xlab("Pack Size") +
  ylab("Deviation") +
  geom_hline(yintercept=0, linetype = "dotted")+
  theme(axis.text.x = element_text(size=12), axis.title = element_text(size=14) ) + 
  theme(axis.text.y = element_text(size=12)) + 
  theme(panel.grid.minor=element_blank(), panel.grid.major=element_blank())

condvalPS<-lm(condval ~ as.numeric(YearPackSize), subset(dd, as.numeric(YearPackSize) >0))
summary(condvalPS)
```
